apiVersion: v1
kind: Service
metadata:
    name: snoymancom
    labels:
        name: snoymancom
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
    selector:
        name: snoymancom
