name: snoymancom

dependencies:
- base
- bytestring
- yaml
- aeson
- markdown
- cmark-gfm
- text
- shakespeare
- blaze-markup
- yesod-static
- yesod-core >=1.4.30
- deepseq
- vector
- filepath
- yesod-newsfeed
- containers
- directory
- time
- conduit
- http-conduit
- xml-conduit
- xml-hamlet
- http-types
- wai
- blaze-html
- warp
- yesod-gitrev
- rio
- auto-update

library:
  source-dirs: src

executables:
  snoymancom:
    main: main.hs
    source-dirs: app
    ghc-options: -threaded
    dependencies:
    - snoymancom
    when:
    - condition: flag(library-only)
      buildable: false

flags:
  library-only:
    description: Only build library
    manual: true
    default: false
