apiVersion: v1
kind: ReplicationController
metadata:
    name: snoymancom
    labels:
        name: snoymancom
spec:
  replicas: 2
  selector:
    name: snoymancom
  template:
    metadata:
        labels:
            name: snoymancom
    spec:
        containers:
        - name: snoymancom
          image: snoyberg/snoyman.com:latest
          resources:
            limits:
              memory: 800Mi
          command: ["snoymancom"]
          ports:
          - containerPort: 3000
            hostPort: 3000
          env:
          - name: PORT
            value: "3000"
          livenessProbe:
              httpGet:
                  path: /
                  port: 3000
